import { _ as __makeTemplateObject } from '../../tslib.es6-30a7ce49.js';
import styled from '@emotion/styled';

var VideoContainer = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  background: ", ";\n  padding: 0px;\n  margin-bottom: 10px;\n  //border: 1px solid ", ";\n  box-shadow: ", ";\n  border-radius: 10px;\n  position: relative;\n"], ["\n  background: ", ";\n  padding: 0px;\n  margin-bottom: 10px;\n  //border: 1px solid ", ";\n  box-shadow: ", ";\n  border-radius: 10px;\n  position: relative;\n"])), function (props) { return props.theme.inversed_color; }, function (props) { return props.theme.dante_control_color; }, function (props) { return props.theme.dante_menu_box_shadow; });
var VideoBody = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  padding-bottom: 20px;\n"], ["\n  padding-bottom: 20px;\n"])));
var green = "#00ab6b";
var red = "#e61742";
var gray = "#bbbbbb";
var RecordActivity = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  background: ", ";\n  position: absolute;\n  height: 13px;\n  width: 13px;\n  border-radius: 50%;\n  display: inline-block;\n  position: absolute;\n  top: 58px;\n  right: 25px;\n  box-shadow: inset -1px -2px 14px 0px #841744;\n"], ["\n  background: ", ";\n  position: absolute;\n  height: 13px;\n  width: 13px;\n  border-radius: 50%;\n  display: inline-block;\n  position: absolute;\n  top: 58px;\n  right: 25px;\n  box-shadow: inset -1px -2px 14px 0px #841744;\n"])), function (props) { return (props.active ? red : green); });
var EditorControls = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  position: absolute;\n  display: -webkit-box;\n  display: -webkit-flex;\n  display: -ms-flexbox;\n  display: -webkit-box;\n  display: -webkit-flex;\n  display: -ms-flexbox;\n  display: flex;\n  -ms-flex-align: center;\n  -ms-flex-pack: center;\n  //margin-top: 25px;\n  //margin-left: 17px;\n  height: 84%;\n  z-index: 10;\n  width: 100%;\n  align-items: center;\n  justify-content: center;\n  flex-direction: column;\n  .controls-recording {\n    position: relative;\n    display: flex;\n    align-items: center;\n  }\n"], ["\n  position: absolute;\n  display: -webkit-box;\n  display: -webkit-flex;\n  display: -ms-flexbox;\n  display: -webkit-box;\n  display: -webkit-flex;\n  display: -ms-flexbox;\n  display: flex;\n  -ms-flex-align: center;\n  -ms-flex-pack: center;\n  //margin-top: 25px;\n  //margin-left: 17px;\n  height: 84%;\n  z-index: 10;\n  width: 100%;\n  align-items: center;\n  justify-content: center;\n  flex-direction: column;\n  .controls-recording {\n    position: relative;\n    display: flex;\n    align-items: center;\n  }\n"])));
var StatusBar = styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  z-index: 10;\n  position: absolute;\n  height: 80%;\n  width: 100%;\n  background: ", ";\n  display: ", ";\n  align-items: center;\n\n  opacity: ", ";\n"], ["\n  z-index: 10;\n  position: absolute;\n  height: 80%;\n  width: 100%;\n  background: ", ";\n  display: ", ";\n  align-items: center;\n\n  opacity: ", ";\n"])), function (props) { return (props.loading ? "white" : "transparent"); }, function (props) { return (props.loading ? "flex" : "none"); }, function (props) { return (props.loading ? "0.9" : "1"); });
var VideoPlayer = styled.video(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  width: 100%;\n  background: black;\n"], ["\n  width: 100%;\n  background: black;\n"])));
var SecondsLeft = styled.div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  //position: absolute;\n  font-size: 1rem;\n  right: 39px;\n  top: 19px;\n  font-size: 2em;\n  color: white;\n"], ["\n  //position: absolute;\n  font-size: 1rem;\n  right: 39px;\n  top: 19px;\n  font-size: 2em;\n  color: white;\n"])));
var RecButton = styled.div(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  display: inline-block;\n  cursor: pointer;\n  -webkit-transition: all 0.25s ease;\n  transition: all 0.25s ease;\n  margin: 7px 17px;\n  text-indent: 36px;\n\n  text-indent: 36px;\n  color: #d9ece5;\n  text-shadow: 0px 1px 0px #101010;\n\n  &:hover {\n    //color: ", "\n    color: #d9ece5;\n  }\n\n  &:before {\n    position: absolute;\n    width: 26px;\n    height: 26px;\n    top: 15px;\n    content: \"\";\n    border-radius: 50px;\n    background: #e80415;\n    cursor: pointer;\n    left: 16px;\n  }\n\n  &.recording {\n    &:before {\n      position: absolute;\n      width: 26px;\n      height: 26px;\n      top: 15px;\n      content: \"\";\n      border-radius: 50px;\n      background: #e80415;\n      cursor: pointer;\n      left: 16px;\n    }\n  }\n\n  &:after {\n    position: absolute;\n    width: 30px;\n    height: 30px;\n    top: 19px;\n    left: 19px;\n    content: \"\";\n    -webkit-transform: translate(-6px, -6px);\n    -ms-transform: translate(-6px, -6px);\n    -webkit-transform: translate(-6px, -6px);\n    -ms-transform: translate(-6px, -6px);\n    -webkit-transform: translate(-6px, -6px);\n    -ms-transform: translate(-6px, -6px);\n    transform: translate(-6px, -6px);\n    border-radius: 50%;\n    border: 2px solid #fff;\n    cursor: pointer;\n  }\n"], ["\n  display: inline-block;\n  cursor: pointer;\n  -webkit-transition: all 0.25s ease;\n  transition: all 0.25s ease;\n  margin: 7px 17px;\n  text-indent: 36px;\n\n  text-indent: 36px;\n  color: #d9ece5;\n  text-shadow: 0px 1px 0px #101010;\n\n  &:hover {\n    //color: ", "\n    color: #d9ece5;\n  }\n\n  &:before {\n    position: absolute;\n    width: 26px;\n    height: 26px;\n    top: 15px;\n    content: \"\";\n    border-radius: 50px;\n    background: #e80415;\n    cursor: pointer;\n    left: 16px;\n  }\n\n  &.recording {\n    &:before {\n      position: absolute;\n      width: 26px;\n      height: 26px;\n      top: 15px;\n      content: \"\";\n      border-radius: 50px;\n      background: #e80415;\n      cursor: pointer;\n      left: 16px;\n    }\n  }\n\n  &:after {\n    position: absolute;\n    width: 30px;\n    height: 30px;\n    top: 19px;\n    left: 19px;\n    content: \"\";\n    -webkit-transform: translate(-6px, -6px);\n    -ms-transform: translate(-6px, -6px);\n    -webkit-transform: translate(-6px, -6px);\n    -ms-transform: translate(-6px, -6px);\n    -webkit-transform: translate(-6px, -6px);\n    -ms-transform: translate(-6px, -6px);\n    transform: translate(-6px, -6px);\n    border-radius: 50%;\n    border: 2px solid #fff;\n    cursor: pointer;\n  }\n"])), green);
var Button = styled.button(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  margin: 11px;\n  outline: none;\n  height: 37px;\n  /* margin-right: 10px; */\n  /* text-align: center; */\n  border-radius: 40px;\n  background: ", ";\n  border: 2px solid ", ";\n  color: #ffffff;\n  -webkit-letter-spacing: 1px;\n  -moz-letter-spacing: 1px;\n  -ms-letter-spacing: 1px;\n  letter-spacing: 1px;\n  text-shadow: 0;\n  cursor: pointer;\n  -webkit-transition: all 0.25s ease;\n  transition: all 0.25s ease;\n\n  font-size: 12px;\n  font-weight: bold;\n  padding-left: 11px;\n  padding-right: 11px;\n\n  cursor: pointer;\n  transition: all 0.25s ease;\n  &:hover {\n    color: white;\n    background: ", ";\n  }\n  &:active {\n    //letter-spacing: 2px;\n    letter-spacing: 2px;\n  }\n  //&:after {\n  //  content:\"SUBMIT\";\n  //}\n\n  &.onclic {\n    width: 24px !important;\n    border-color: ", ";\n    border-width: 3px;\n    font-size: 0;\n    border-left-color: ", ";\n    animation: rotating 2s 0.25s linear infinite;\n\n    &:after {\n      content: \"\";\n    }\n    &:hover {\n      color: $green;\n      background: white;\n    }\n  }\n\n  &.right {\n    float: right;\n    margin-right: 26px;\n  }\n\n  @keyframes rotating {\n    from {\n      transform: rotate(0deg);\n    }\n    to {\n      transform: rotate(360deg);\n    }\n  }\n"], ["\n  margin: 11px;\n  outline: none;\n  height: 37px;\n  /* margin-right: 10px; */\n  /* text-align: center; */\n  border-radius: 40px;\n  background: ", ";\n  border: 2px solid ", ";\n  color: #ffffff;\n  -webkit-letter-spacing: 1px;\n  -moz-letter-spacing: 1px;\n  -ms-letter-spacing: 1px;\n  letter-spacing: 1px;\n  text-shadow: 0;\n  cursor: pointer;\n  -webkit-transition: all 0.25s ease;\n  transition: all 0.25s ease;\n\n  font-size: 12px;\n  font-weight: bold;\n  padding-left: 11px;\n  padding-right: 11px;\n\n  cursor: pointer;\n  transition: all 0.25s ease;\n  &:hover {\n    color: white;\n    background: ", ";\n  }\n  &:active {\n    //letter-spacing: 2px;\n    letter-spacing: 2px;\n  }\n  //&:after {\n  //  content:\"SUBMIT\";\n  //}\n\n  &.onclic {\n    width: 24px !important;\n    border-color: ", ";\n    border-width: 3px;\n    font-size: 0;\n    border-left-color: ", ";\n    animation: rotating 2s 0.25s linear infinite;\n\n    &:after {\n      content: \"\";\n    }\n    &:hover {\n      color: $green;\n      background: white;\n    }\n  }\n\n  &.right {\n    float: right;\n    margin-right: 26px;\n  }\n\n  @keyframes rotating {\n    from {\n      transform: rotate(0deg);\n    }\n    to {\n      transform: rotate(360deg);\n    }\n  }\n"])), green, green, green, gray, green);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9;

export { Button, EditorControls, RecButton, RecordActivity, SecondsLeft, StatusBar, VideoBody, VideoContainer, VideoPlayer };
